-- ============================================================================
-- IDMS — Interior Design Management System
-- Database schema + demo data
-- Engine: MySQL 8+ / MariaDB 10.4+   Charset: utf8mb4
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `idms_interior`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `idms_interior`;

-- ----------------------------------------------------------------------------
-- admins
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(190) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('super_admin','editor') NOT NULL DEFAULT 'editor',
  `last_login_at` DATETIME NULL,
  `failed_attempts` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `locked_until` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Default dev login: admin@idms.local / Admin@12345 (CHANGE BEFORE LAUNCH)
INSERT INTO `admins` (`name`,`email`,`password_hash`,`role`) VALUES
('Studio Admin','admin@idms.local','$2y$10$Kx1sQ8lZ4Y0mN3vC7fH2FOeYQ1qzQxU8pJj6tA5nQ2rL3wX9dB1a','super_admin');
-- NOTE: hash above is a placeholder and is regenerated by install.php on first run.

-- ----------------------------------------------------------------------------
-- settings (single-row key/value config, editable from admin — no code edits)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `setting_key` VARCHAR(100) PRIMARY KEY,
  `setting_value` TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `settings` (`setting_key`,`setting_value`) VALUES
('company_name','Aura Interiors'),
('tagline','Spaces Designed to Inspire'),
('logo_path',''),
('favicon_path',''),
('phone','+92 300 1234567'),
('whatsapp_number','923001234567'),
('whatsapp_default_message','Assalamualaikum, I am interested in your interior design services. I would like to discuss my project.'),
('email','hello@aurainteriors.pk'),
('address','Plot 12, Street 5, F-7 Markaz, Islamabad, Pakistan'),
('google_maps_url','https://maps.google.com/?q=Islamabad'),
('facebook_url','https://facebook.com/'),
('instagram_url','https://instagram.com/'),
('tiktok_url',''),
('youtube_url',''),
('business_hours','Mon – Sat: 10:00 AM – 8:00 PM'),
('hero_heading','Spaces Designed to Inspire.'),
('hero_subheading','Transforming homes, offices, restaurants and commercial spaces into beautiful environments designed around the way you live and work.'),
('hero_image',''),
('about_image',''),
('cta_text','Book a Free Consultation'),
('stat_years','10+'),
('stat_projects','150+'),
('stat_clients','50+'),
('stat_cities','6'),
('google_analytics_id',''),
('cities','Islamabad,Rawalpindi,Lahore,Karachi,Gujranwala,Faisalabad,Peshawar,Multan'),
('meta_title','Aura Interiors — Premium Interior Design Studio in Pakistan'),
('meta_description','Aura Interiors designs premium homes, offices, restaurants and commercial spaces across Pakistan. Book a free consultation today.');

-- ----------------------------------------------------------------------------
-- social_links (structured alternative for footer icons ordering)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `social_links`;
CREATE TABLE `social_links` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `platform` VARCHAR(40) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `icon_class` VARCHAR(60) NOT NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `social_links` (`platform`,`url`,`icon_class`,`sort_order`) VALUES
('Facebook','https://facebook.com/','fa-brands fa-facebook-f',1),
('Instagram','https://instagram.com/','fa-brands fa-instagram',2),
('YouTube','','fa-brands fa-youtube',3),
('TikTok','','fa-brands fa-tiktok',4);

-- ----------------------------------------------------------------------------
-- services
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `services`;
CREATE TABLE `services` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(170) NOT NULL UNIQUE,
  `short_description` VARCHAR(500) NULL,
  `content` TEXT NULL,
  `image_path` VARCHAR(255) NULL,
  `icon_class` VARCHAR(60) NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_services_published` (`is_published`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `services` (`title`,`slug`,`short_description`,`content`,`image_path`,`icon_class`,`sort_order`) VALUES
('Residential Interior Design','residential-interior-design','Complete interior design solutions for houses, apartments and luxury residences.','Full-service residential design covering space planning, materials, lighting, furniture selection and execution — tailored to how your family actually lives.','assets/images/demo/service-residential.jpg','fa-solid fa-house',1),
('Commercial Interior Design','commercial-interior-design','Modern spaces for offices, businesses and corporate environments.','We design commercial environments that reflect brand identity while remaining functional, efficient and welcoming for staff and clients alike.','assets/images/demo/service-commercial.jpg','fa-solid fa-building',2),
('Restaurant & Cafe Design','restaurant-cafe-design','Beautiful and functional spaces designed around customer experience.','From layout flow to ambience and material selection, we design food and beverage spaces that keep guests coming back.','assets/images/demo/service-restaurant.jpg','fa-solid fa-utensils',3),
('Office Interior Design','office-interior-design','Professional workplaces designed for productivity and brand identity.','Workplace design that balances collaboration, focus and brand storytelling — built around your team''s workflow.','assets/images/demo/service-office.jpg','fa-solid fa-briefcase',4),
('Architecture & Space Planning','architecture-space-planning','Thoughtful layouts combining functionality and aesthetics.','Structural and spatial planning that forms the foundation of every successful interior — before a single finish is chosen.','assets/images/demo/service-architecture.jpg','fa-solid fa-drafting-compass',5),
('Turnkey Interior Solutions','turnkey-interior-solutions','From concept and design to execution and finishing.','A single point of accountability from concept to final handover — design, procurement, construction and styling under one roof.','assets/images/demo/service-turnkey.jpg','fa-solid fa-key',6);

-- ----------------------------------------------------------------------------
-- projects
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `projects`;
CREATE TABLE `projects` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(180) NOT NULL,
  `slug` VARCHAR(200) NOT NULL UNIQUE,
  `category` ENUM('Residential','Commercial','Office','Restaurant','Bedroom','Kitchen','Living Room','Luxury Interiors') NOT NULL,
  `location` VARCHAR(120) NULL,
  `property_type` VARCHAR(80) NULL,
  `area_sqft` INT UNSIGNED NULL,
  `completion_year` YEAR NULL,
  `short_description` VARCHAR(500) NULL,
  `description` TEXT NULL,
  `cover_image` VARCHAR(255) NULL,
  `video_url` VARCHAR(255) NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  `views` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_projects_cat` (`category`),
  INDEX `idx_projects_published` (`is_published`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `projects` (`title`,`slug`,`category`,`location`,`property_type`,`area_sqft`,`completion_year`,`short_description`,`description`,`cover_image`,`is_featured`,`sort_order`) VALUES
('Modern Islamabad Residence','modern-islamabad-residence','Residential','Islamabad','House',4200,2025,'A warm, minimalist family home built around natural light and texture.','This four-bedroom residence in Islamabad was reimagined with a restrained material palette — white oak, matte stone and brushed brass — to create calm, light-filled living spaces for a young family. Every room was planned around how the family actually moves through the home.','assets/images/demo/project-islamabad-residence.jpg',1,1),
('Luxury Bahria Town Villa','luxury-bahria-town-villa','Luxury Interiors','Rawalpindi','Villa',6800,2024,'An opulent villa interior blending classic proportions with contemporary finishes.','A statement villa in Bahria Town designed for entertaining, featuring a double-height living hall, custom joinery and a curated art and lighting scheme throughout.','assets/images/demo/project-bahria-villa.jpg',1,2),
('Contemporary Corporate Office','contemporary-corporate-office','Office','Lahore','Corporate HQ',9500,2025,'A productivity-focused workplace with a strong brand identity.','Designed for a fast-growing tech company, this HQ balances open collaboration zones with quiet focus rooms, unified by the client''s brand palette.','assets/images/demo/project-corporate-office.jpg',1,3),
('Minimalist Karachi Apartment','minimalist-karachi-apartment','Residential','Karachi','Apartment',1800,2024,'A compact apartment made spacious through smart, minimal design.','Clever storage, a soft neutral palette and multi-functional furniture transformed this two-bedroom apartment into an airy retreat.','assets/images/demo/project-karachi-apartment.jpg',0,4),
('Modern Fine-Dining Restaurant','modern-fine-dining-restaurant','Restaurant','Lahore','Restaurant',3200,2025,'An intimate dining room designed around mood lighting and texture.','Rich walnut, brass detailing and layered lighting create an intimate, memorable dining experience for this Lahore restaurant.','assets/images/demo/project-restaurant.jpg',1,5),
('Boutique Cafe Interior','boutique-cafe-interior','Restaurant','Islamabad','Cafe',1400,2024,'A light-filled, Instagram-ready cafe with a distinct visual identity.','Terrazzo counters, greenery and warm oak seating give this cafe a relaxed, editorial feel that matches its brand.','assets/images/demo/project-cafe.jpg',0,6),
('Executive Office Suite','executive-office-suite','Office','Islamabad','Office',2600,2025,'A refined executive floor designed to impress clients and empower leadership.','Rich materials and considered lighting create an executive floor that feels both authoritative and welcoming.','assets/images/demo/project-executive-office.jpg',0,7),
('Serene Master Bedroom Suite','serene-master-bedroom-suite','Bedroom','Lahore','House',450,2024,'A hotel-inspired master suite built for rest.','A calming palette of stone, linen and soft wood creates a hotel-style master suite designed purely for rest and recovery.','assets/images/demo/project-bedroom.jpg',0,8),
('Chef-Style Modern Kitchen','chef-style-modern-kitchen','Kitchen','Islamabad','House',380,2025,'A functional, chef-inspired kitchen with premium finishes.','Handleless cabinetry, a waterfall-edge island and integrated appliances make this kitchen as functional as it is beautiful.','assets/images/demo/project-kitchen.jpg',1,9),
('Elegant Formal Living Room','elegant-formal-living-room','Living Room','Rawalpindi','House',600,2024,'A formal living room balancing tradition and contemporary comfort.','Classic proportions, a muted palette and custom furniture give this formal living room quiet, lasting elegance.','assets/images/demo/project-living-room.jpg',0,10),
('Commercial Retail Showroom','commercial-retail-showroom','Commercial','Karachi','Retail',5200,2025,'A retail environment engineered to showcase product and drive footfall.','Considered lighting, wayfinding and materials work together to create a retail showroom built to convert browsers into buyers.','assets/images/demo/project-retail.jpg',0,11),
('Boutique Hotel Lobby','boutique-hotel-lobby','Commercial','Lahore','Hospitality',3800,2024,'A striking arrival experience for a boutique hotel brand.','A dramatic material and lighting story sets the tone for guest arrival in this boutique hotel lobby.','assets/images/demo/project-hotel-lobby.jpg',1,12);

-- ----------------------------------------------------------------------------
-- project_images (gallery per project)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `project_images`;
CREATE TABLE `project_images` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `project_id` INT UNSIGNED NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  `caption` VARCHAR(255) NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT `fk_pimg_project` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE,
  INDEX `idx_pimg_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `project_images` (`project_id`,`image_path`,`caption`,`sort_order`) VALUES
(1,'assets/images/demo/project-islamabad-residence.jpg','Living room','1'),
(1,'assets/images/demo/project-islamabad-residence.jpg','Dining area','2'),
(2,'assets/images/demo/project-bahria-villa.jpg','Main hall','1'),
(3,'assets/images/demo/project-corporate-office.jpg','Open workspace','1'),
(5,'assets/images/demo/project-restaurant.jpg','Dining hall','1');

-- ----------------------------------------------------------------------------
-- before_after
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `before_after`;
CREATE TABLE `before_after` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `project_name` VARCHAR(180) NOT NULL,
  `description` VARCHAR(500) NULL,
  `before_image` VARCHAR(255) NOT NULL,
  `after_image` VARCHAR(255) NOT NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `before_after` (`project_name`,`description`,`before_image`,`after_image`,`sort_order`) VALUES
('Islamabad Residence — Living Room','A dated living room transformed into a bright, minimalist family space.','assets/images/demo/before-livingroom.jpg','assets/images/demo/after-livingroom.jpg',1),
('Karachi Apartment — Kitchen','A closed, cramped kitchen opened into a modern chef-style layout.','assets/images/demo/before-kitchen.jpg','assets/images/demo/after-kitchen.jpg',2),
('Lahore Villa — Master Bedroom','A plain bedroom reimagined as a hotel-inspired retreat.','assets/images/demo/before-bedroom.jpg','assets/images/demo/after-bedroom.jpg',3);

-- ----------------------------------------------------------------------------
-- gallery (standalone media library, independent of specific projects)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `gallery`;
CREATE TABLE `gallery` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(180) NULL,
  `media_type` ENUM('image','video') NOT NULL DEFAULT 'image',
  `file_path` VARCHAR(255) NOT NULL,
  `category` VARCHAR(80) NULL,
  `caption` VARCHAR(255) NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `gallery` (`title`,`media_type`,`file_path`,`category`,`caption`,`sort_order`) VALUES
('Living Room Detail','image','assets/images/demo/gallery-1.jpg','Living Room','Custom joinery detail',1),
('Kitchen Island','image','assets/images/demo/gallery-2.jpg','Kitchen','Waterfall-edge island',2),
('Office Lounge','image','assets/images/demo/gallery-3.jpg','Office','Breakout lounge seating',3),
('Restaurant Ambience','image','assets/images/demo/gallery-4.jpg','Restaurant','Evening ambience lighting',4),
('Bedroom Styling','image','assets/images/demo/gallery-5.jpg','Bedroom','Layered textile styling',5),
('Facade Detail','image','assets/images/demo/gallery-6.jpg','Architecture','Exterior material detail',6);

-- ----------------------------------------------------------------------------
-- testimonials
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `testimonials`;
CREATE TABLE `testimonials` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `client_name` VARCHAR(150) NOT NULL,
  `review` TEXT NOT NULL,
  `project_type` VARCHAR(120) NULL,
  `location` VARCHAR(120) NULL,
  `rating` TINYINT UNSIGNED NOT NULL DEFAULT 5,
  `photo_path` VARCHAR(255) NULL,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `testimonials` (`client_name`,`review`,`project_type`,`location`,`rating`,`sort_order`) VALUES
('Ayesha Raza','The team completely understood our vision and delivered beyond what we imagined. Professional from the first meeting to final handover.','Residential — House','Islamabad',5,1),
('Bilal Ahmed','Our office feels completely different now — clients comment on it every week. Execution was on time and on budget.','Office Interior','Lahore',5,2),
('Sana Malik','They transformed our restaurant into something guests actively talk about. Worth every rupee.','Restaurant Design','Lahore',5,3),
('Omar Farooq','Communication throughout the project was excellent — no surprises, no delays. Highly recommend for any commercial project.','Commercial','Karachi',5,4);

-- ----------------------------------------------------------------------------
-- team_members
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `team_members`;
CREATE TABLE `team_members` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(150) NOT NULL,
  `position` VARCHAR(150) NULL,
  `bio` TEXT NULL,
  `photo_path` VARCHAR(255) NULL,
  `facebook_url` VARCHAR(255) NULL,
  `instagram_url` VARCHAR(255) NULL,
  `linkedin_url` VARCHAR(255) NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `team_members` (`name`,`position`,`bio`,`photo_path`,`sort_order`) VALUES
('Hina Sheikh','Founder & Principal Designer','Hina leads every project''s creative direction, with over 12 years designing residential and hospitality interiors across Pakistan.','assets/images/demo/team-1.jpg',1),
('Ahmed Khan','Head of Architecture','Ahmed oversees space planning and structural coordination, ensuring every design is as functional as it is beautiful.','assets/images/demo/team-2.jpg',2),
('Zoya Tariq','Senior Interior Designer','Zoya specialises in residential styling and material curation, bringing warmth and detail to every space.','assets/images/demo/team-3.jpg',3),
('Usman Siddiqui','Project Execution Manager','Usman manages on-site execution and vendor coordination, keeping every project on schedule and on budget.','assets/images/demo/team-4.jpg',4);

-- ----------------------------------------------------------------------------
-- blog_categories
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `blog_categories`;
CREATE TABLE `blog_categories` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(120) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `blog_categories` (`name`,`slug`) VALUES
('Design Trends','design-trends'),
('Cost & Planning','cost-and-planning'),
('Kitchens','kitchens'),
('Living Rooms','living-rooms'),
('Guides','guides');

-- ----------------------------------------------------------------------------
-- blog_posts
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `blog_posts`;
CREATE TABLE `blog_posts` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(220) NOT NULL,
  `slug` VARCHAR(240) NOT NULL UNIQUE,
  `category_id` INT UNSIGNED NULL,
  `featured_image` VARCHAR(255) NULL,
  `excerpt` VARCHAR(500) NULL,
  `content` LONGTEXT NULL,
  `author_name` VARCHAR(120) NULL,
  `seo_title` VARCHAR(220) NULL,
  `seo_description` VARCHAR(320) NULL,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `published_at` DATETIME NULL,
  `views` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_blog_category` FOREIGN KEY (`category_id`) REFERENCES `blog_categories`(`id`) ON DELETE SET NULL,
  INDEX `idx_blog_published` (`is_published`,`published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `blog_posts` (`title`,`slug`,`category_id`,`featured_image`,`excerpt`,`content`,`author_name`,`seo_title`,`seo_description`,`is_published`,`published_at`) VALUES
('10 Modern Living Room Ideas for Pakistani Homes','10-modern-living-room-ideas-for-pakistani-homes',4,'assets/images/demo/blog-1.jpg','Fresh, practical living room ideas suited to Pakistani homes and lifestyles.','<p>A modern living room should balance comfort, culture and clean design. Here are ten ideas our studio uses across projects in Islamabad, Lahore and Karachi...</p><h2>1. Layered lighting</h2><p>Combine ambient, task and accent lighting rather than relying on a single ceiling fixture.</p><h2>2. A neutral base with texture</h2><p>Use texture — linen, wood grain, textured plaster — instead of heavy colour to add depth.</p>','Hina Sheikh','10 Modern Living Room Ideas for Pakistani Homes | Aura Interiors','Practical, modern living room design ideas tailored to Pakistani homes, from our design studio.',1,'2026-06-01 10:00:00'),
('How Much Does Interior Design Cost in Pakistan?','how-much-does-interior-design-cost-in-pakistan',2,'assets/images/demo/blog-2.jpg','A transparent look at what shapes interior design pricing in Pakistan.','<p>Interior design costs in Pakistan vary widely based on scope, finishes and property size. In this guide we break down the main cost factors...</p><h2>What affects the budget</h2><p>Area, material grade, custom joinery and execution complexity are the biggest drivers of cost.</p>','Ahmed Khan','Interior Design Cost in Pakistan — A Transparent Guide','What actually drives interior design costs in Pakistan, explained by our design team.',1,'2026-06-10 10:00:00'),
('Modern Kitchen Design Ideas','modern-kitchen-design-ideas',3,'assets/images/demo/blog-3.jpg','Functional and beautiful kitchen design ideas for modern Pakistani homes.','<p>The kitchen has become the heart of the modern Pakistani home. Here''s how we approach functional, beautiful kitchen design...</p>','Zoya Tariq','Modern Kitchen Design Ideas | Aura Interiors','Functional, beautiful modern kitchen design ideas from our design studio.',1,'2026-06-18 10:00:00'),
('Best Interior Design Trends for 2026','best-interior-design-trends-for-2026',1,'assets/images/demo/blog-4.jpg','The interior design trends shaping homes and offices in 2026.','<p>From warm minimalism to biophilic design, here are the trends our studio is seeing across residential and commercial projects in 2026...</p>','Hina Sheikh','Best Interior Design Trends for 2026','The interior design trends shaping Pakistani homes and offices in 2026.',1,'2026-07-02 10:00:00'),
('How to Choose the Right Interior Designer','how-to-choose-the-right-interior-designer',5,'assets/images/demo/blog-5.jpg','Practical questions to ask before hiring an interior designer in Pakistan.','<p>Choosing the right interior designer is one of the most important decisions in a renovation. Here''s what to look for...</p>','Usman Siddiqui','How to Choose the Right Interior Designer in Pakistan','A practical guide to choosing the right interior designer for your project in Pakistan.',1,'2026-07-20 10:00:00');

-- ----------------------------------------------------------------------------
-- inquiries (leads captured from the consultation form)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `inquiries`;
CREATE TABLE `inquiries` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `full_name` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `whatsapp` VARCHAR(30) NULL,
  `email` VARCHAR(190) NULL,
  `city` VARCHAR(100) NULL,
  `project_type` VARCHAR(60) NULL,
  `property_type` VARCHAR(60) NULL,
  `area` VARCHAR(60) NULL,
  `budget` VARCHAR(60) NULL,
  `start_date` DATE NULL,
  `message` TEXT NULL,
  `status` ENUM('NEW','CONTACTED','IN DISCUSSION','CONVERTED','NOT INTERESTED','CLOSED') NOT NULL DEFAULT 'NEW',
  `source_page` VARCHAR(190) NULL,
  `ip_address` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_inquiries_status` (`status`),
  INDEX `idx_inquiries_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- analytics_events (lightweight internal tracking — page views / clicks)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `analytics_events`;
CREATE TABLE `analytics_events` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `event_type` ENUM('page_view','project_view','whatsapp_click','call_click','inquiry_submit') NOT NULL,
  `reference` VARCHAR(190) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_events_type_date` (`event_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- process_steps (the "Our Process" section, editable)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `process_steps`;
CREATE TABLE `process_steps` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `step_number` TINYINT UNSIGNED NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `description` VARCHAR(400) NULL,
  `icon_class` VARCHAR(60) NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `process_steps` (`step_number`,`title`,`description`,`icon_class`,`sort_order`) VALUES
(1,'Consultation','We start with a free consultation to understand your needs, style and budget.','fa-solid fa-comments',1),
(2,'Site Visit','Our team visits your space to take measurements and assess the site in person.','fa-solid fa-house-circle-check',2),
(3,'Concept & Design','We present mood boards, layouts and 3D concepts tailored to your brief.','fa-solid fa-pen-ruler',3),
(4,'Execution','Our production team handles procurement, construction and installation.','fa-solid fa-hard-hat',4),
(5,'Final Handover','We walk through the finished space with you before final handover.','fa-solid fa-key',5);

-- ----------------------------------------------------------------------------
-- why_choose_us
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS `why_choose_us`;
CREATE TABLE `why_choose_us` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(120) NOT NULL,
  `description` VARCHAR(400) NULL,
  `icon_class` VARCHAR(60) NULL,
  `sort_order` SMALLINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `why_choose_us` (`title`,`description`,`icon_class`,`sort_order`) VALUES
('Experienced Designers','A decade of design experience across residential and commercial projects.','fa-solid fa-user-tie',1),
('Premium Materials','We source and vet premium, durable materials for every project.','fa-solid fa-gem',2),
('Customized Designs','No templates — every space is designed around you.','fa-solid fa-shapes',3),
('Transparent Process','Clear timelines and pricing with no hidden surprises.','fa-solid fa-file-invoice',4),
('Attention to Detail','From joinery to lighting, every detail is considered.','fa-solid fa-magnifying-glass',5),
('End-to-End Execution','Design and build handled under one accountable team.','fa-solid fa-people-carry-box',6),
('Dedicated Project Management','A single point of contact managing your project start to finish.','fa-solid fa-clipboard-list',7),
('On-Time Delivery','We plan realistically and deliver on the timelines we commit to.','fa-solid fa-clock',8);

SET FOREIGN_KEY_CHECKS = 1;
